-- =============================================================================
-- Async execution jobs for large price changes (FD volume: up to 400K SKUs).
-- Run AFTER db/schema.sql. Prefix must match (default FDPM_).
-- =============================================================================
DEFINE P = FDPM_

CREATE SEQUENCE &P.SEQ_PC_JOB START WITH 1 INCREMENT BY 1 CACHE 50;

CREATE TABLE &P.PC_JOB (
  JOB_ID      NUMBER(12)   NOT NULL,
  PC_ID       NUMBER(12)   NOT NULL,
  JOB_TYPE    VARCHAR2(20) NOT NULL,   -- RESOLVE | PROMOTE
  STATUS      VARCHAR2(20) DEFAULT 'QUEUED' NOT NULL, -- QUEUED|RUNNING|DONE|FAILED
  SKU_COUNT   NUMBER(12),
  STORE_COUNT NUMBER(12),
  MESSAGE     VARCHAR2(2000),
  CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  STARTED_AT  TIMESTAMP,
  FINISHED_AT TIMESTAMP,
  CONSTRAINT &P.PK_PC_JOB PRIMARY KEY (JOB_ID),
  CONSTRAINT &P.CK_PC_JOB_TYPE   CHECK (JOB_TYPE IN ('RESOLVE','PROMOTE')),
  CONSTRAINT &P.CK_PC_JOB_STATUS CHECK (STATUS IN ('QUEUED','RUNNING','DONE','FAILED')),
  CONSTRAINT &P.FK_PC_JOB_PC FOREIGN KEY (PC_ID) REFERENCES &P.LOC_LIST_PRICE_CHANGE (PC_ID) ON DELETE CASCADE
);
CREATE INDEX &P.IX_PC_JOB_PC ON &P.PC_JOB (PC_ID);
CREATE INDEX &P.IX_PC_JOB_STATUS ON &P.PC_JOB (STATUS);
