-- Pricing zones (read-only, from RPM).

SELECT
  zg.ZONE_GROUP_ID    AS ZONE_GROUP_ID,
  zg.ZONE_GROUP_NAME  AS ZONE_GROUP_NAME,
  z.ZONE_ID           AS ZONE_ID,
  z.ZONE_NAME         AS ZONE_NAME,
  zl.LOCATION         AS STORE_ID
FROM RMS.RPM_ZONE_GROUP   zg
JOIN RMS.RPM_ZONE         z  ON z.ZONE_GROUP_ID = zg.ZONE_GROUP_ID
JOIN RMS.RPM_ZONE_LOCATION zl ON zl.ZONE_ID      = z.ZONE_ID
WHERE zg.ZONE_GROUP_ID = NVL(:p_zone_group_id, zg.ZONE_GROUP_ID)
ORDER BY zg.ZONE_GROUP_ID, z.ZONE_ID, zl.LOCATION;
